name: CI

on:
  push:
    branches: [ main ]

jobs:
  build_push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}:latest
