name: CI

on:
  push:
    branches: [ main ]

jobs:
  push_to_registry:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: akiraohgaki
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: akiraohgaki/devcontainer:latest
